// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using untitled1.Data;

#nullable disable

namespace untitled1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516112530_AddIsTVSeries")]
    partial class AddIsTVSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hành Động"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kinh Dị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viễn Tưởng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tình Cảm"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTVSeries")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Genre = "Action",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = false,
                            Title = "Avengers: Endgame",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Genre = "Action",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = false,
                            Title = "John Wick 4",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Genre = "Horror",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = false,
                            Title = "The Conjuring",
                            Year = 2013
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = false,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Genre = "Romance",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = false,
                            Title = "La La Land",
                            Year = 2016
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Genre = "Drama/Action",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = true,
                            Title = "Breaking Bad",
                            Year = 2008
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Genre = "Horror/Fantasy",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            Title = "Wednesday",
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Genre = "Thriller",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = true,
                            Title = "Squid Game",
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Genre = "Action",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = false,
                            Title = "Spider-Man: NWH",
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = true,
                            Title = "Stranger Things",
                            Year = 2016
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Genre = "Thriller",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = false,
                            Title = "Parasite",
                            Year = 2019
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/3.jpg",
                            IsTVSeries = false,
                            Title = "Dune: Part Two",
                            Year = 2024
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Genre = "Drama",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = true,
                            Title = "The Last of Us",
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Genre = "Crime",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = true,
                            Title = "Peaky Blinders",
                            Year = 2013
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Genre = "Fantasy",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = true,
                            Title = "The Witcher",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Genre = "Crime",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            Title = "Money Heist",
                            Year = 2017
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Genre = "Drama",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = false,
                            Title = "Joker",
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Genre = "Crime",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = true,
                            Title = "Ozark",
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
