// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using untitled1.Data;

#nullable disable

namespace untitled1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608140606_AddMovieRatingAndLocalTrailer")]
    partial class AddMovieRatingAndLocalTrailer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("untitled1.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PremiumEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PremiumStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hành Động"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kinh Dị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viễn Tưởng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tình Cảm"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kịch Tính"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hoạt Hình"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Phiêu Lưu"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeNumber = 1,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "Pilot (Tập Mở Đầu)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeNumber = 2,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "Cat's in the Bag... (Chiếc túi bí mật)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeNumber = 3,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "...And the Bag's in the River (Bí ẩn trôi sông)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 4,
                            EpisodeNumber = 1,
                            MovieId = 1,
                            SeasonNumber = 2,
                            Title = "Seven Thirty-Seven (Chuyến bay 737)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 5,
                            EpisodeNumber = 1,
                            MovieId = 2,
                            SeasonNumber = 1,
                            Title = "Winter Is Coming (Mùa đông đang đến)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 6,
                            EpisodeNumber = 2,
                            MovieId = 2,
                            SeasonNumber = 1,
                            Title = "The Kingsroad (Con đường hoàng gia)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 7,
                            EpisodeNumber = 1,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Wednesday's Child Is Full of Woe (Đứa trẻ ngày Thứ Tư)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 8,
                            EpisodeNumber = 2,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Woe Is the Loneliest Number (Cô độc nhất)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 9,
                            EpisodeNumber = 3,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Friend or Woe (Bạn hay thù)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 10,
                            EpisodeNumber = 1,
                            MovieId = 9,
                            SeasonNumber = 1,
                            Title = "Red Light, Green Light (Đèn đỏ, đèn xanh)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 11,
                            EpisodeNumber = 2,
                            MovieId = 9,
                            SeasonNumber = 1,
                            Title = "Hell (Địa ngục)",
                            VideoUrl = "/videos/sample.mp4"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTVSeries")
                        .HasColumnType("bit");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Bryan Cranston, Aaron Paul, Anna Gunn",
                            Description = "Một giáo viên hóa học cấp ba bị chẩn đoán mắc bệnh ung thư phổi giai đoạn cuối quyết định bắt tay với một cựu học sinh để sản xuất và bán ma túy đá chất lượng cao nhằm bảo đảm tài chính cho gia đình.",
                            Director = "Vince Gilligan",
                            Genre = "Kịch tính / Hình sự",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = true,
                            Rating = 9.5,
                            Title = "Breaking Bad",
                            TrailerUrl = "https://www.youtube.com/embed/HhesaQXLuRY",
                            TrailerVideoUrl = "/videos/trailers/breaking_bad.mp4",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Emilia Clarke, Kit Harington, Peter Dinklage",
                            Description = "Chín gia tộc quý tộc chiến đấu để giành quyền kiểm soát vùng đất giả tưởng Westeros, trong khi một kẻ thù cổ xưa đang thức tỉnh sau hàng thiên niên kỷ ngủ yên dưới bức tường băng tuyết phía Bắc.",
                            Director = "David Benioff",
                            Genre = "Hành động / Kỳ ảo / Phiêu lưu",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = true,
                            Rating = 9.1999999999999993,
                            Title = "Game of Thrones",
                            TrailerUrl = "https://www.youtube.com/embed/KPLYYLDtMJ0",
                            Year = 2011
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Cillian Murphy, Emily Blunt, Matt Damon",
                            Description = "Câu chuyện về nhà vật lý lý thuyết J. Robert Oppenheimer, người lãnh đạo Dự án Manhattan chế tạo ra quả bom nguyên tử đầu tiên cho nhân loại, mở ra thời đại hạt nhân và những dằn vặt đạo đức khôn nguôi.",
                            Director = "Christopher Nolan",
                            Genre = "Kịch tính / Tiểu sử / Lịch sử",
                            ImageUrl = "/images/movies/3.jpg",
                            IsTVSeries = false,
                            Rating = 8.4000000000000004,
                            Title = "Oppenheimer",
                            TrailerUrl = "https://www.youtube.com/embed/uYPbbksJxIg",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Cast = "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
                            Description = "Biệt đội siêu anh hùng Avengers và các đồng minh phải sẵn sàng hy sinh tất cả để cố gắng đánh bại Thanos quyền năng trước khi hắn hủy diệt một nửa vũ trụ bằng sáu Viên đá Vô cực.",
                            Director = "Anthony Russo, Joe Russo",
                            Genre = "Hành động / Viễn tưởng / Phiêu lưu",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = false,
                            Rating = 8.4000000000000004,
                            Title = "Avengers: Infinity War",
                            TrailerUrl = "https://www.youtube.com/embed/6ZfuNTqbHE8",
                            Year = 2018
                        },
                        new
                        {
                            Id = 5,
                            Cast = "Brad Pitt, Edward Norton, Helena Bonham Carter",
                            Description = "Một nhân viên văn phòng mất ngủ triền miên và một người bán xà phòng lập dị thành lập một câu lạc bộ đánh lộn ngầm đầy bạo lực, dần biến tướng thành một tổ chức vô chính phủ chống lại chủ nghĩa tiêu dùng.",
                            Director = "David Fincher",
                            Genre = "Kịch tính / Giật gân",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = false,
                            Rating = 8.8000000000000007,
                            Title = "Fight Club",
                            TrailerUrl = "https://www.youtube.com/embed/qtR39562a1g",
                            Year = 1999
                        },
                        new
                        {
                            Id = 6,
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Description = "Khi mối đe dọa mang tên Joker xuất hiện tàn phá thành phố Gotham, Người Dơi phải chấp nhận những thử thách tâm lý và thể xác tột cùng để duy trì ranh giới mong manh giữa công lý và thù hận.",
                            Director = "Christopher Nolan",
                            Genre = "Hành động / Kịch tính / Tội phạm",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            Rating = 9.0,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/LDG9bisJEaI",
                            Year = 2008
                        },
                        new
                        {
                            Id = 7,
                            Cast = "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
                            Description = "Trong tương lai khi Trái Đất sắp bị hủy diệt bởi nạn đói, một nhóm các nhà du hành vũ trụ dấn thân vào chuyến đi xuyên hố đen vũ trụ để tìm kiếm một mái nhà mới cho nhân loại.",
                            Director = "Christopher Nolan",
                            Genre = "Viễn tưởng / Phiêu lưu / Kịch tính",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = false,
                            Rating = 8.6999999999999993,
                            Title = "Interstellar",
                            TrailerUrl = "https://www.youtube.com/embed/zSWdZATo3cA",
                            TrailerVideoUrl = "/videos/trailers/interstellar.mp4",
                            Year = 2014
                        },
                        new
                        {
                            Id = 8,
                            Cast = "Jenna Ortega, Gwendoline Christie, Riki Lindhome",
                            Description = "Wednesday Addams theo học tại Học viện Nevermore, nơi cô cố gắng làm chủ năng lượng ngoại cảm của mình, phá giải một vụ án giết người hàng loạt kinh hoàng và khám phá bí ẩn gia đình 25 năm trước.",
                            Director = "Tim Burton",
                            Genre = "Kinh dị / Kỳ ảo / Kịch tính",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            Rating = 8.0999999999999996,
                            Title = "Wednesday",
                            TrailerUrl = "https://www.youtube.com/embed/Di310WS8zLk",
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            Cast = "Lee Jung-jae, Park Hae-soo, Wi Ha-jun",
                            Description = "Hàng trăm người chơi nợ nần chồng chất chấp nhận lời mời kỳ lạ tham gia các trò chơi dân gian dành cho trẻ em với giải thưởng hấp dẫn, nhưng thất bại đồng nghĩa với cái chết ngay lập tức.",
                            Director = "Hwang Dong-hyuk",
                            Genre = "Hành động / Giật gân / Kịch tính",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = true,
                            Rating = 8.0,
                            Title = "Squid Game",
                            TrailerUrl = "https://www.youtube.com/embed/oqxAJKy0R4A",
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Cast = "Tom Holland, Zendaya, Benedict Cumberbatch",
                            Description = "Danh tính siêu anh hùng của Peter Parker bị tiết lộ. Anh tìm đến Doctor Strange để làm phép xóa ký ức mọi người, vô tình xé rách đa vũ trụ và kéo theo những phản diện huyền thoại từ các thế giới khác.",
                            Director = "Jon Watts",
                            Genre = "Hành động / Viễn tưởng / Phiêu lưu",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = false,
                            Rating = 8.1999999999999993,
                            Title = "Spider-Man: No Way Home",
                            TrailerUrl = "https://www.youtube.com/embed/JfVOs4VSpmA",
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            Cast = "Timothée Chalamet, Zendaya, Rebecca Ferguson",
                            Description = "Paul Atreides hợp lực cùng Chani và người Fremen trên con đường phục thù những kẻ đã hủy hoại gia tộc mình, đối mặt với sự giằng xé giữa tình yêu của đời mình và số phận của vũ trụ.",
                            Director = "Denis Villeneuve",
                            Genre = "Viễn tưởng / Phiêu lưu / Hành động",
                            ImageUrl = "/images/hero/hero2.jpg",
                            IsTVSeries = false,
                            Rating = 8.5999999999999996,
                            Title = "Dune: Part Two",
                            TrailerUrl = "https://www.youtube.com/embed/U2Qp5pL3ovA",
                            TrailerVideoUrl = "/videos/trailers/dune2.mp4",
                            Year = 2024
                        },
                        new
                        {
                            Id = 12,
                            Cast = "Keanu Reeves, Donnie Yen, Bill Skarsgård",
                            Description = "John Wick tìm ra con đường đánh bại Hội Tối Cao để giành lại tự do cho bản thân, đối đầu với một liên minh sát thủ toàn cầu mới và những người bạn cũ nay ở hai đầu chiến tuyến.",
                            Director = "Chad Stahelski",
                            Genre = "Hành động / Giật gân",
                            ImageUrl = "/images/hero/hero3.jpg",
                            IsTVSeries = false,
                            Rating = 7.7000000000000002,
                            Title = "John Wick: Chapter 4",
                            TrailerUrl = "https://www.youtube.com/embed/qEVUardwtLH",
                            TrailerVideoUrl = "/videos/trailers/john_wick4.mp4",
                            Year = 2023
                        },
                        new
                        {
                            Id = 13,
                            Cast = "Robert Pattinson, Zoë Kravitz, Jeffrey Wright",
                            Description = "Trong năm thứ hai chống tội phạm ở Gotham, Batman dấn thân vào cuộc điều tra các vụ giết người hàng loạt của gã điên Riddler, phơi bày những bê bối tham nhũng chôn giấu từ lâu của thành phố.",
                            Director = "Matt Reeves",
                            Genre = "Hành động / Hình sự / Kịch tính",
                            ImageUrl = "/images/hero/hero4.jpg",
                            IsTVSeries = false,
                            Rating = 7.7999999999999998,
                            Title = "The Batman",
                            TrailerUrl = "https://www.youtube.com/embed/mqq_HDEH518",
                            TrailerVideoUrl = "/videos/trailers/the_batman.mp4",
                            Year = 2022
                        },
                        new
                        {
                            Id = 14,
                            Cast = "Shameik Moore, Jake Johnson, Hailee Steinfeld",
                            Description = "Miles Morales, một thiếu niên da màu ở Brooklyn, vô tình có siêu năng lực nhện và phải hợp tác với những Người Nhện khác từ các chiều không gian song song để giải cứu New York.",
                            Director = "Bob Persichetti, Peter Ramsey, Rodney Rothman",
                            Genre = "Hoạt hình / Hành động / Phiêu lưu",
                            ImageUrl = "/images/hero/hero5.jpg",
                            IsTVSeries = false,
                            Rating = 8.4000000000000004,
                            Title = "Spider-Man: Into the Spider-Verse",
                            TrailerUrl = "https://www.youtube.com/embed/g4Hbz2jLxLk",
                            Year = 2018
                        },
                        new
                        {
                            Id = 15,
                            Cast = "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
                            Description = "Cô bé Chihiro đi lạc vào thế giới linh hồn kỳ lạ, nơi cha mẹ cô bị biến thành heo. Cô phải làm việc tại nhà tắm của mụ phù thủy Yubaba và tìm cách giải cứu gia đình mình.",
                            Director = "Hayao Miyazaki",
                            Genre = "Hoạt hình / Phiêu lưu / Kỳ ảo",
                            ImageUrl = "/images/hero/hero6.jpg",
                            IsTVSeries = false,
                            Rating = 8.5999999999999996,
                            Title = "Spirited Away",
                            TrailerUrl = "https://www.youtube.com/embed/ByXuk9QqQkk",
                            Year = 2001
                        },
                        new
                        {
                            Id = 16,
                            Cast = "Sam Worthington, Zoe Saldana, Sigourney Weaver",
                            Description = "Nhiều năm sau cuộc chiến đầu tiên, Jake Sully và Neytiri phải rời bỏ quê hương rừng xanh để tìm kiếm nơi trú ẩn tại bộ tộc vùng biển đảo Pandora trước mối hiểm họa xâm lăng mới.",
                            Director = "James Cameron",
                            Genre = "Viễn tưởng / Hành động / Phiêu lưu",
                            ImageUrl = "/images/hero/hero7.jpg",
                            IsTVSeries = false,
                            Rating = 7.5999999999999996,
                            Title = "Avatar: The Way of Water",
                            TrailerUrl = "https://www.youtube.com/embed/d9MyW72ELq0",
                            Year = 2022
                        },
                        new
                        {
                            Id = 17,
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
                            Description = "Một kẻ trộm chuyên nghiệp chuyên xâm nhập vào tiềm thức của mục tiêu thông qua giấc mơ để đánh cắp bí mật kinh doanh, nay nhận nhiệm vụ đảo ngược: cấy một ý tưởng vào tâm trí đối thủ.",
                            Director = "Christopher Nolan",
                            Genre = "Viễn tưởng / Hành động / Giật gân",
                            ImageUrl = "/images/hero/hero8.jpg",
                            IsTVSeries = false,
                            Rating = 8.8000000000000007,
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/embed/YoHD9XEInc0",
                            Year = 2010
                        },
                        new
                        {
                            Id = 18,
                            Cast = "Jay Baruchel, Gerard Butler, America Ferrera",
                            Description = "Hiccup, một cậu bé Viking yếu ớt sống trên đảo Berk vốn có truyền thống diệt rồng, vô tình bắt được một chú rồng loài Night Fury quý hiếm và nhận ra rồng không đáng sợ như họ vẫn tưởng.",
                            Director = "Dean DeBlois, Chris Sanders",
                            Genre = "Hoạt hình / Phiêu lưu / Hài hước",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = false,
                            Rating = 8.0999999999999996,
                            Title = "How to Train Your Dragon",
                            TrailerUrl = "https://www.youtube.com/embed/fTlrTevG1-I",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 11,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 12,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 14,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 14,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 15,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 15,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 16,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 16,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 17,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 18,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/movies/2.jpg",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/movies/2.jpg",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/movies/3.jpg",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/movies/3.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/movies/4.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/movies/5.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/movies/4.jpg",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/movies/5.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/movies/6.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/images/movies/6.jpg",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "/images/movies/8.jpg",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "/images/movies/8.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "/images/movies/9.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "/images/movies/9.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "/images/hero/hero2.jpg",
                            MovieId = 11
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "/images/hero/hero3.jpg",
                            MovieId = 12
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "/images/hero/hero4.jpg",
                            MovieId = 13
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "/images/hero/hero5.jpg",
                            MovieId = 14
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "/images/hero/hero6.jpg",
                            MovieId = 15
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("untitled1.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlanId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("untitled1.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpatialAudio")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScreens")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#6b7280",
                            HasDownload = false,
                            HasSpatialAudio = false,
                            IsPopular = false,
                            MaxScreens = 1,
                            Name = "Cơ Bản",
                            Price = 79000m,
                            Resolution = "480p SD",
                            Tagline = "Xem phim chất lượng tốt"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#e50914",
                            HasDownload = true,
                            HasSpatialAudio = true,
                            IsPopular = true,
                            MaxScreens = 2,
                            Name = "Tiêu Chuẩn",
                            Price = 149000m,
                            Resolution = "1080p Full HD",
                            Tagline = "Full HD & Âm thanh không gian"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#f59e0b",
                            HasDownload = true,
                            HasSpatialAudio = true,
                            IsPopular = false,
                            MaxScreens = 4,
                            Name = "Cao Cấp",
                            Price = 219000m,
                            Resolution = "4K Ultra HD + HDR",
                            Tagline = "4K Ultra HD + HDR + Dolby Atmos"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("untitled1.Models.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("untitled1.Models.Entities.ViewingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WatchTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewingHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("untitled1.Models.Entities.Episode", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("Episodes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieCategory", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieImage", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("MovieImages")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Order", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("untitled1.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("untitled1.Models.Entities.UserSubscription", b =>
                {
                    b.HasOne("untitled1.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("untitled1.Models.Entities.ViewingHistory", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("MovieCategories");

                    b.Navigation("MovieImages");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("untitled1.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
