// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using untitled1.Data;

#nullable disable

namespace untitled1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525145215_AddMovieDescriptionTrailer")]
    partial class AddMovieDescriptionTrailer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("untitled1.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hành Động"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kinh Dị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viễn Tưởng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tình Cảm"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kịch Tính"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeNumber = 1,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "Pilot (Tập Mở Đầu)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeNumber = 2,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "Cat's in the Bag... (Chiếc túi bí mật)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeNumber = 3,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "...And the Bag's in the River (Bí ẩn trôi sông)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 4,
                            EpisodeNumber = 1,
                            MovieId = 1,
                            SeasonNumber = 2,
                            Title = "Seven Thirty-Seven (Chuyến bay 737)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 5,
                            EpisodeNumber = 1,
                            MovieId = 2,
                            SeasonNumber = 1,
                            Title = "Winter Is Coming (Mùa đông đang đến)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 6,
                            EpisodeNumber = 2,
                            MovieId = 2,
                            SeasonNumber = 1,
                            Title = "The Kingsroad (Con đường hoàng gia)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 7,
                            EpisodeNumber = 1,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Wednesday's Child Is Full of Woe (Đứa trẻ ngày Thứ Tư)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 8,
                            EpisodeNumber = 2,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Woe Is the Loneliest Number (Cô độc nhất)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 9,
                            EpisodeNumber = 3,
                            MovieId = 8,
                            SeasonNumber = 1,
                            Title = "Friend or Woe (Bạn hay thù)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 10,
                            EpisodeNumber = 1,
                            MovieId = 9,
                            SeasonNumber = 1,
                            Title = "Red Light, Green Light (Đèn đỏ, đèn xanh)",
                            VideoUrl = "/videos/sample.mp4"
                        },
                        new
                        {
                            Id = 11,
                            EpisodeNumber = 2,
                            MovieId = 9,
                            SeasonNumber = 1,
                            Title = "Hell (Địa ngục)",
                            VideoUrl = "/videos/sample.mp4"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTVSeries")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Crime/Drama",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = true,
                            Title = "Breaking Bad",
                            TrailerUrl = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Action/Fantasy",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = true,
                            Title = "Game of Thrones",
                            TrailerUrl = "",
                            Year = 2011
                        },
                        new
                        {
                            Id = 3,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Drama/History",
                            ImageUrl = "/images/movies/3.jpg",
                            IsTVSeries = false,
                            Title = "Oppenheimer",
                            TrailerUrl = "",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Action/Sci-Fi",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = false,
                            Title = "Avengers: Infinity War",
                            TrailerUrl = "",
                            Year = 2018
                        },
                        new
                        {
                            Id = 5,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Drama/Thriller",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = false,
                            Title = "Fight Club",
                            TrailerUrl = "",
                            Year = 1999
                        },
                        new
                        {
                            Id = 6,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Action/Drama",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            Title = "The Dark Knight",
                            TrailerUrl = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = 7,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Sci-Fi/Drama",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = false,
                            Title = "Interstellar",
                            TrailerUrl = "",
                            Year = 2014
                        },
                        new
                        {
                            Id = 8,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Horror/Fantasy",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            Title = "Wednesday",
                            TrailerUrl = "",
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Action/Thriller",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = true,
                            Title = "Squid Game",
                            TrailerUrl = "",
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Cast = "",
                            Description = "",
                            Director = "",
                            Genre = "Action/Sci-Fi",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = false,
                            Title = "Spider-Man: No Way Home",
                            TrailerUrl = "",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/movies/2.jpg",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/movies/2.jpg",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/movies/3.jpg",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/movies/3.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/movies/4.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/movies/5.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/movies/4.jpg",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/movies/5.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/movies/6.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/images/movies/still_action.png",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/images/movies/6.jpg",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/images/movies/7.jpg",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "/images/movies/8.jpg",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "/images/movies/8.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "/images/movies/9.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "/images/movies/9.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "/images/movies/still_scifi.png",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "/images/movies/10.jpg",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "/images/movies/1.jpg",
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("untitled1.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("untitled1.Models.Entities.Episode", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("Episodes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieCategory", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.MovieImage", b =>
                {
                    b.HasOne("untitled1.Models.Entities.Movie", "Movie")
                        .WithMany("MovieImages")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("MovieCategories");

                    b.Navigation("MovieImages");
                });
#pragma warning restore 612, 618
        }
    }
}
