// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using untitled1.Data;

#nullable disable

namespace untitled1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("untitled1.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hành Động"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kinh Dị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viễn Tưởng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tình Cảm"
                        });
                });

            modelBuilder.Entity("untitled1.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTVSeries")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The Avengers assemble once more in order to restore order to the universe.",
                            Genre = "Action",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "Avengers: Endgame",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "John Wick uncovers a path to defeating The High Table.",
                            Genre = "Action",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "John Wick 4",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence.",
                            Genre = "Horror",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = false,
                            IsTrending = false,
                            Title = "The Conjuring",
                            Year = 2013
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            IsTrending = false,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "While navigating their careers in Los Angeles, a pianist and an actress fall in love.",
                            Genre = "Romance",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = false,
                            IsTrending = false,
                            Title = "La La Land",
                            Year = 2016
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
                            Genre = "Drama/Action",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "Breaking Bad",
                            Year = 2008
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability.",
                            Genre = "Horror/Fantasy",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "Wednesday",
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.",
                            Genre = "Thriller",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "Squid Game",
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help.",
                            Genre = "Action",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "Spider-Man: NWH",
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/1.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "Stranger Things",
                            Year = 2016
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Genre = "Thriller",
                            ImageUrl = "/images/movies/2.jpg",
                            IsTVSeries = false,
                            IsTrending = false,
                            Title = "Parasite",
                            Year = 2019
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/3.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "Dune: Part Two",
                            Year = 2024
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl.",
                            Genre = "Drama",
                            ImageUrl = "/images/movies/4.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "The Last of Us",
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.",
                            Genre = "Crime",
                            ImageUrl = "/images/movies/5.jpg",
                            IsTVSeries = true,
                            IsTrending = false,
                            Title = "Peaky Blinders",
                            Year = 2013
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Genre = "Sci-Fi",
                            ImageUrl = "/images/movies/6.jpg",
                            IsTVSeries = false,
                            IsTrending = false,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
                            Genre = "Fantasy",
                            ImageUrl = "/images/movies/7.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "The Witcher",
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "An unusual group of robbers attempt to carry out the most perfect heist in Spanish history.",
                            Genre = "Crime",
                            ImageUrl = "/images/movies/8.jpg",
                            IsTVSeries = true,
                            IsTrending = true,
                            Title = "Money Heist",
                            Year = 2017
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "A mentally troubled comedian is disregarded and mistreated by society.",
                            Genre = "Drama",
                            ImageUrl = "/images/movies/9.jpg",
                            IsTVSeries = false,
                            IsTrending = true,
                            Title = "Joker",
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "A financial advisor drags his family from Chicago to the Missouri Ozarks.",
                            Genre = "Crime",
                            ImageUrl = "/images/movies/10.jpg",
                            IsTVSeries = true,
                            IsTrending = false,
                            Title = "Ozark",
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
